routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('component/content');
})->name('landing');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/pengajuan', [App\Http\Controllers\NikahController::class, 'pengajuan'])->name('pengajuan');

Route::namespace('App\Http\Controllers')->name('nikah.')->middleware(['web'])->prefix('nikah')->group(function () {
    Route::get('/tanggal', [App\Http\Controllers\NikahController::class, 'Date'])->name('date');
    Route::post('/tanggal', [App\Http\Controllers\NikahController::class, 'DateSumbit'])->name('dateSubmit');
    Route::get('/daftar', [App\Http\Controllers\NikahController::class, 'redirect'])->name('redirect');

    Route::get('/pilih', [App\Http\Controllers\NikahController::class, 'Pilih'])->name('pilih');

    Route::post('/pilih', [App\Http\Controllers\NikahController::class, 'verifikasisubmit'])->name('verifikasiSubmit');


    Route::name('cowo.')->prefix('cowo')->group(function () {
        Route::get('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1Biodatacowo'])->name('S1Biodatacowo');
        Route::post('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1BiodatacowoSubmit'])->name('S1BiodatacowoSubmit');
        Route::get('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2Asalusulcowo'])->name('S2Asalusulcowo');
        Route::post('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2AsalusulcowoSubmit'])->name('S2AsalusulcowoSubmit');
        Route::get('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicowo'])->name('S3PersetujuanMempelaicowo');
        Route::post('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicowoSubmit'])->name('S3PersetujuanMempelaicowoSubmit');
        Route::get('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucowo'])->name('S4suketortucowo');
        Route::post('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucowoSubmit'])->name('S4suketortucowoSubmit');
        Route::get('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincowo'])->name('S5sujincowo');
        Route::post('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincowoSubmit'])->name('S5sujincowoSubmit');
        Route::get('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcowo'])->name('S6sukematcowo');
        Route::post('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcowoSubmit'])->name('S6sukematcowoSubmit');
    });

    Route::name('cewe.')->prefix('cewe')->group(function () {
        Route::get('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1Biodatacewe'])->name('S1Biodatacewe');
        Route::post('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1BiodataceweSubmit'])->name('S1BiodataceweSubmit');
        Route::get('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2Asalusulcewe'])->name('S2Asalusulcewe');
        Route::post('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2AsalusulceweSubmit'])->name('S2AsalusulceweSubmit');
        Route::get('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicewe'])->name('S3PersetujuanMempelaicewe');
        Route::post('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaiceweSubmit'])->name('S3PersetujuanMempelaiceweSubmit');
        Route::get('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucewe'])->name('S4suketortucewe');
        Route::post('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortuceweSubmit'])->name('S4suketortuceweSubmit');
        Route::get('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincewe'])->name('S5sujincewe');
        Route::post('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujinceweSubmit'])->name('S5sujinceweSubmit');
        Route::get('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcewe'])->name('S6sukematcewe');
        Route::post('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematceweSubmit'])->name('S6sukematceweSubmit');
    });
});

resources/views/component/daftar/form/jadwal.blade.php
@extends('landing')

@section('styles')
@endsection

@section('content')
    <style>
        .form-control{
            border: 1px solid #2c89e7;
        }
    </style>

    <div class="">
        <div class="container ">
            <br><br>
            @include('component.daftar.app')
            <br>

            <form method="post" action="{{route('nikah.dateSubmit')}}">
                @csrf
                <div class="row mx-0">
                <div class="col-12">
                    <fieldset>
                        <legend class="font-weight-bold SourceSansPro biru-tua">Pengajuan Tanggal Nikah</legend>
                        <div class="row">
                            <div class="col-sm-6 biru">
                                <div class="form-group">
                                    <label class="font-weight-bold">Hari <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="day" value="{{($data != null) ? $data->day : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                 </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Tanggal Pernikahan <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input class="form-control" type="date" value="{{($data != null) ? \Carbon\Carbon::parse($data->date)->format('Y-m-d') : '' }}" name="date" id="example-date-input">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Jam Pernikahan <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input class="form-control" type="time" name="time" value="{{($data != null) ? $data->time : '' }}" id="example-time-input">
                                </div>
                            </div>
                            <div class="col-sm-6 biru">
                                <div class="form-group">
                                    <label class="font-weight-bold">Mas Kawin <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="dowry" value="{{($data != null) ? $data->dowry : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Mas Kawin...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Utang ?  <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <!-- Default switch -->
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" name="debt" class="custom-control-input" id="customSwitches" {{($data != null && $data->debt == 1) ? 'checked' : '' }}>
                                        <label class="custom-control-label" for="customSwitches"></label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Tempat <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" value="{{($data != null) ? $data->place : '' }}" name="place" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Temat...">
                                </div>
                            </div>

                        </div>

                    </fieldset>
                </div>
            </div>
            <div class="text-center mt-3">
                <button type="submit" href="" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Yey Nikah</button>
            </div>
            </form>
            <br>
        </div>
    </div>
@endsection

resources/views/component/daftar/form/pilih.blade.php
@extends('landing')

@section('content')
    <div class="">
        <div class="container ">
            <br><br>
            <h1 class="biru-tua text-center SourceSansPro">Lengkapi Formulir Pengajuan Nikah</h1>
            <br><br>
            <div class="row" style="height: 500px">
                <div class="col-md-6 align-self-center text-center">
                    <a href="{{route('nikah.cowo.S1Biodatacowo')}}"><img src="{{asset('img/caloncowo.png')}}" width="250" class="img-fluid" alt="" style="padding-bottom: 50px"></a>
                </div>
                <div class="col-md-6 SourceSansPro align-self-center text-center ">
                    <a href="{{route('nikah.cewe.S1Biodatacewe')}}"><img src="{{asset('img/caloncewe.png')}}" width="250" class="img-fluid" alt="" style="padding-bottom: 50px">
                    </a>
                </div>
            </div>
            <div class="text-center mt-3">
                @if($data->biodata_male_id ==null || $data->biodata_female_id ==null)
                    <a href="{{route('nikah.date')}}" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Back</a>
                @else
                    <div class="row">
                        <div class="col-md-6 ">
                            <a href="{{route('nikah.date')}}" class="btn btn-primary float-right" style="width: 200px;background-color: #2a92d7">Back</a>
                        </div>
                        <div class="col-md-6">
                            <form action="{{route('nikah.verifikasiSubmit')}}" class="float-left" method="post">
                                @csrf
                                <input type="text" value="1" name="final" hidden>
                                <a class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Finish</a>
                            </form>
                        </div>
                    </div>

                @endif

            </div>
            <br><br>
        </div>

    </div>
@endsection

resources/views/component/daftar/form/step.blade.php
<style>
    .sipora-step {
        border: 1px solid #1377be;
        border-radius: 15px;
        color: #1377be;
        height: 150px;
    }
    .sipora-step.active {
        background: #eee;
    }

    .sipora-step.done {
        color: white;
        background: #22E21B;
        border: 1px solid #22E21B;
    }
    .sipora-step.index {
        border: 1px solid #1377be;
        border-radius: 15px;
        color: white;
        background: #1377be
    }

    fieldset {
        border: 2px solid #1377be !important;
        border-radius: 15px;
        padding: 0 1.4em 1.4em 1.4em !important;
        margin: 0 0 1.5em 0 !important;
    }
    legend {
        width: inherit;
        padding: 0 10px;
        border-bottom: none;
    }

    .sipora-badge {
        border-radius: 15px;
        color: white;
        width: auto;
        font-weight: 100 !important;
        font-family: 'Raleway-Regular';
    }
    .sipora-badge.red {
        background: #FB2626;
    }
    .sipora-badge.green {
        background: #22E21B;
    }
    .step-round{
        padding: 7px;padding-top: 10px;padding-bottom: 10px ;background-color: white
    }
    .step-round-blank{
        padding: 7px;padding-top: 10px;padding-bottom: 10px ;background-color: white
    }
    .border-step{
        border: 2px #1377be solid !important;
    }

    @media (max-width: 992px) {
        .text-step{
            font-size: 10px;
        }
    }


</style>
<div class="row">
   <div class="col-md-2 col-sm-4">
       <div>
           <fieldset class="bg-biru pt-4 text-center">
               <span class="border border-white rounded-circle biru font-weight-bold step-round">N-1</span>
               <br><br>
               <span class="font-weight-bold text-white SourceSansPro text-step">DATA DIRI</span>
           </fieldset>
       </div>
   </div>
    <div class="col-md-2 col-sm-4">
        <div>
            <fieldset class=" pt-4 text-center">
                <span class="border border-primary rounded-circle biru font-weight-bold step-round-blank border-step">N-2</span>
                <br><br>
                <span class="text-justify text-center font-weight-bold biru SourceSansPro text-step">ASAL - USUL</span>
            </fieldset>
        </div>
    </div>
    <div class="col-md-2 col-sm-4">
        <div>
            <fieldset class=" pt-4 text-center">
                <span class="border border-primary rounded-circle biru font-weight-bold step-round-blank border-step">N-3</span>
                <br><br>
                <span class="font-weight-bold biru SourceSansPro text-step">PERSETUJUAN</span>
            </fieldset>
        </div>
    </div>
    <div class="col-md-2 col-sm-4">
        <div>
            <fieldset class=" pt-4 text-center">
                <span class="border border-primary rounded-circle biru font-weight-bold step-round-blank border-step">N-4</span>
                <br><br>
                <span class="font-weight-bold biru SourceSansPro text-step">KETERANGAN</span>
            </fieldset>
        </div>
    </div>
    <div class="col-md-2 col-sm-4">
        <div>
            <fieldset class=" pt-4 text-center">
                <span class="border border-primary rounded-circle biru font-weight-bold step-round-blank border-step">N-5</span>
                <br><br>
                <span class="font-weight-bold biru SourceSansPro text-step">SURAT IJIN</span>
            </fieldset>
        </div>
    </div>
    <div class="col-md-2 col-sm-4">
        <div>
            <fieldset class=" pt-4 text-center">
                <span class="border border-primary rounded-circle biru font-weight-bold step-round-blank border-step">N-6</span>
                <br><br>
                <span class="font-weight-bold biru SourceSansPro text-step">KEMATIAN</span>
            </fieldset>
        </div>
    </div>
</div>