routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('component/content');
})->name('landing');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/pengajuan', [App\Http\Controllers\NikahController::class, 'pengajuan'])->name('pengajuan');

Route::namespace('App\Http\Controllers')->name('nikah.')->middleware(['web'])->prefix('nikah')->group(function () {
    Route::get('/tanggal', [App\Http\Controllers\NikahController::class, 'Date'])->name('date');
    Route::post('/tanggal', [App\Http\Controllers\NikahController::class, 'DateSumbit'])->name('dateSubmit');
    Route::get('/daftar', [App\Http\Controllers\NikahController::class, 'redirect'])->name('redirect');

    Route::get('/pilih', [App\Http\Controllers\NikahController::class, 'Pilih'])->name('pilih');

    Route::post('/pilih', [App\Http\Controllers\NikahController::class, 'verifikasisubmit'])->name('verifikasiSubmit');


    Route::name('cowo.')->prefix('cowo')->group(function () {
        Route::get('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1Biodatacowo'])->name('S1Biodatacowo');
        Route::post('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1BiodatacowoSubmit'])->name('S1BiodatacowoSubmit');
        Route::get('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2Asalusulcowo'])->name('S2Asalusulcowo');
        Route::post('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2AsalusulcowoSubmit'])->name('S2AsalusulcowoSubmit');
        Route::get('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicowo'])->name('S3PersetujuanMempelaicowo');
        Route::post('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicowoSubmit'])->name('S3PersetujuanMempelaicowoSubmit');
        Route::get('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucowo'])->name('S4suketortucowo');
        Route::post('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucowoSubmit'])->name('S4suketortucowoSubmit');
        Route::get('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincowo'])->name('S5sujincowo');
        Route::post('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincowoSubmit'])->name('S5sujincowoSubmit');
        Route::get('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcowo'])->name('S6sukematcowo');
        Route::post('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcowoSubmit'])->name('S6sukematcowoSubmit');
    });

    Route::name('cewe.')->prefix('cewe')->group(function () {
        Route::get('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1Biodatacewe'])->name('S1Biodatacewe');
        Route::post('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1BiodataceweSubmit'])->name('S1BiodataceweSubmit');
        Route::get('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2Asalusulcewe'])->name('S2Asalusulcewe');
        Route::post('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2AsalusulceweSubmit'])->name('S2AsalusulceweSubmit');
        Route::get('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicewe'])->name('S3PersetujuanMempelaicewe');
        Route::post('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaiceweSubmit'])->name('S3PersetujuanMempelaiceweSubmit');
        Route::get('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucewe'])->name('S4suketortucewe');
        Route::post('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortuceweSubmit'])->name('S4suketortuceweSubmit');
        Route::get('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincewe'])->name('S5sujincewe');
        Route::post('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujinceweSubmit'])->name('S5sujinceweSubmit');
        Route::get('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcewe'])->name('S6sukematcewe');
        Route::post('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematceweSubmit'])->name('S6sukematceweSubmit');
    });
});

resources/views/component/content.blade.php
@extends('landing')

@section('content')
<div class="">
    <div class="container ">
        <div class="row" style="height: 550px">

            <div class="col-12 col-md-7 align-self-center text-center">
                <img src="{{asset('img/nikah.png')}}" width="500" class="img-fluid" alt="">
            </div>
            <div class="col-md-5 SourceSansPro align-self-center ">
                <h1 style="color: #838383" class="">
                    Yuk Ajukan Nikah Dengan Lebih Mudah Dengan WEB kondangan
                </h1>
                <br>
                <a href="{{route('nikah.redirect')}}" type="button" class="btn bg-orange text-white pd-20">DAFTAR</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/component/style.blade.php
<!-- Scripts -->
{{-- <script src="{{ asset('js/app.js') }}" defer></script> --}}

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->
{{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
{{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> --}}
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.1.19/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="{{asset('css/style.css')}}">

<link rel="stylesheet" type="text/css" href="{{asset('css/slick/slick.css')}}" />
<link rel="stylesheet" type="text/css" href="{{asset('css/slick/slick-theme.css')}}" />
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">


<script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>


<link rel="stylesheet" type="text/css" href="{{asset('asset-login/fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/vendor/animate/animate.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/vendor/css-hamburgers/hamburgers.min.css')}}">
<!--===============================================================================================-->

<link rel="stylesheet" type="text/css" href="{{asset('asset-login/vendor/animsition/css/animsition.min.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/vendor/select2/select2.min.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/vendor/daterangepicker/daterangepicker.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/css/util.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('asset-login/css/main.css')}}">