routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('component/content');
})->name('landing');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/pengajuan', [App\Http\Controllers\NikahController::class, 'pengajuan'])->name('pengajuan');

Route::namespace('App\Http\Controllers')->name('nikah.')->middleware(['web'])->prefix('nikah')->group(function () {
    Route::get('/tanggal', [App\Http\Controllers\NikahController::class, 'Date'])->name('date');
    Route::post('/tanggal', [App\Http\Controllers\NikahController::class, 'DateSumbit'])->name('dateSubmit');
    Route::get('/daftar', [App\Http\Controllers\NikahController::class, 'redirect'])->name('redirect');

    Route::get('/pilih', [App\Http\Controllers\NikahController::class, 'Pilih'])->name('pilih');

    Route::post('/pilih', [App\Http\Controllers\NikahController::class, 'verifikasisubmit'])->name('verifikasiSubmit');


    Route::name('cowo.')->prefix('cowo')->group(function () {
        Route::get('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1Biodatacowo'])->name('S1Biodatacowo');
        Route::post('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1BiodatacowoSubmit'])->name('S1BiodatacowoSubmit');
        Route::get('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2Asalusulcowo'])->name('S2Asalusulcowo');
        Route::post('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2AsalusulcowoSubmit'])->name('S2AsalusulcowoSubmit');
        Route::get('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicowo'])->name('S3PersetujuanMempelaicowo');
        Route::post('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicowoSubmit'])->name('S3PersetujuanMempelaicowoSubmit');
        Route::get('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucowo'])->name('S4suketortucowo');
        Route::post('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucowoSubmit'])->name('S4suketortucowoSubmit');
        Route::get('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincowo'])->name('S5sujincowo');
        Route::post('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincowoSubmit'])->name('S5sujincowoSubmit');
        Route::get('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcowo'])->name('S6sukematcowo');
        Route::post('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcowoSubmit'])->name('S6sukematcowoSubmit');
    });

    Route::name('cewe.')->prefix('cewe')->group(function () {
        Route::get('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1Biodatacewe'])->name('S1Biodatacewe');
        Route::post('/s1-biodata', [App\Http\Controllers\NikahController::class, 'S1BiodataceweSubmit'])->name('S1BiodataceweSubmit');
        Route::get('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2Asalusulcewe'])->name('S2Asalusulcewe');
        Route::post('/s2-asalusul', [App\Http\Controllers\NikahController::class, 'S2AsalusulceweSubmit'])->name('S2AsalusulceweSubmit');
        Route::get('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaicewe'])->name('S3PersetujuanMempelaicewe');
        Route::post('/s3-persetujuan', [App\Http\Controllers\NikahController::class, 'S3PersetujuanMempelaiceweSubmit'])->name('S3PersetujuanMempelaiceweSubmit');
        Route::get('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortucewe'])->name('S4suketortucewe');
        Route::post('/s4-suketortu', [App\Http\Controllers\NikahController::class, 'S4suketortuceweSubmit'])->name('S4suketortuceweSubmit');
        Route::get('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujincewe'])->name('S5sujincewe');
        Route::post('/s5-sujin', [App\Http\Controllers\NikahController::class, 'S5sujinceweSubmit'])->name('S5sujinceweSubmit');
        Route::get('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematcewe'])->name('S6sukematcewe');
        Route::post('/s6-sukemat', [App\Http\Controllers\NikahController::class, 'S6sukematceweSubmit'])->name('S6sukematceweSubmit');
    });
});

resources/views/component/daftar/form/cewe/s1-biodata.blade.php
@extends('landing')

@section('content')
    <div class="">
        <div class="container ">
            <form action="{{route('nikah.cewe.S1BiodataceweSubmit')}}" method="post">
                @csrf
                <br><br>
            <h1 class="biru-tua text-center SourceSansPro">Selamat Datang </h1>
            <br><br><br><br>
            @include('component.daftar.form.step')
            <br><br>
            <div>
                <div class="row">
                    <div class="col-md-3">
                        <fieldset>
                            <legend class="font-weight-bold SourceSansPro biru-tua">Suket Nikah</legend>
                            <div class="form-group biru">
                                <label class="font-weight-bold">Nomor <a style="font-size: 20px" class="text-danger">*</a></label>
                                <input type="text" class="form-control" name="letter" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->letter : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Nomor...">
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend class="font-weight-bold SourceSansPro biru-tua">Kantor</legend>
                            <div class="form-group biru">
                                <label class="font-weight-bold">Kantor /Desa /Kelurahan <a style="font-size: 20px" class="text-danger">*</a></label>
                                <input type="text" class="form-control" name="village" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->village : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Nomor...">
                            </div>
                            <div class="form-group biru">
                                <label class="font-weight-bold">Kecamatan <a style="font-size: 20px" class="text-danger">*</a></label>
                                <input type="text" class="form-control" name="district" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->district : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Nomor...">
                            </div>
                            <div class="form-group biru">
                                <label class="font-weight-bold">Kabupaten/Kota <a style="font-size: 20px" class="text-danger">*</a></label>
                                <input type="text" class="form-control" name="city" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->city : '' }}" aria-describedby="emailHelp" placeholder="Masukkan Nomor...">
                            </div>
                        </fieldset>
                    </div>
                    <div class="col-md-9">
                        <fieldset>
                            <legend class="font-weight-bold SourceSansPro biru-tua">Data Diri Calon Perempuan</legend>

                            <div class="row">
                                <div class="col-sm-6 biru">
                                    <div class="form-group">
                                        <label class="font-weight-bold">Nama Lengkap <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="full_name" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->full_name : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Nama Alias <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="name" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->name : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Tempat Tanggal Lahir <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <div class="form-row">
                                            <div class="col-md-6">
                                                <input type="text" name="place_of_birth" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->place_of_birth : '' }}" class="form-control" placeholder="Tempat">
                                            </div>
                                            <div class="col-md-6">
                                                <input class="form-control" type="date" value="{{($data->FemaleCandidate != null) ? \Carbon\Carbon::parse($data->FemaleCandidate->date_of_birth)->format('Y-m-d') : '' }}" name="date_of_birth" id="example-date-input">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Warga Negara <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="citizen" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->citizen : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Agama <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <select id="inputState" class="form-control" name="religion">
                                            <option value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->religion : '' }}" selected>{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->religion : '' }}</option>
                                            <option value="islam">Islam</option>
                                            <option value="hindu">hindu</option>
                                            <option value="budha">budha</option>
                                            <option value="krtisten">krtisten</option>
                                            <option value="protestan">protestan</option>
                                            <option value="konghuchu">konghuchu</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="col-sm-6 biru">
                                    <div class="form-group">
                                        <label class="font-weight-bold">Pekerjaan <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="profession" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->profession : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Tempat Tinggal <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="residence" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->residence : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Mas Kawin...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Bin/Binti <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="bin_binti" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->bin_binti : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Mas Kawin...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Status Perkawinan <a style="font-size: 20px" class="text-danger">*</a></label>
                                        <input type="text" class="form-control" name="status" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->status : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Mas Kawin...">
                                    </div>
                                    <div class="form-group">
                                        <label class="font-weight-bold">Nama Suami Dulu <a style="font-size: 20px" class="text-danger"></a></label>
                                        <input type="text" class="form-control" name="ex_spouse" value="{{($data->FemaleCandidate != null) ? $data->FemaleCandidate->ex_spouse : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Mas Kawin...">
                                    </div>
                                </div>

                            </div>

                        </fieldset>
                    </div>
                </div>
            </div>


            <div class="text-center mt-3">
                <a href="{{route('nikah.pilih')}}" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Back</a>
                <button href="{{route('nikah.cewe.S1BiodataceweSubmit')}}" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Next</button>
            </div>
            <br><br>
            </form>
        </div>
    </div>
@endsection

resources/views/component/daftar/form/cewe/s5-sujin.blade.php
@extends('landing')

@section('content')
    <div class="">
        <div class="container ">
            <br><br>
            <h1 class="biru-tua text-center SourceSansPro">Surat Persetujuan Mempelai</h1>
            <br><br><br><br>
            @include('component.daftar.form.step')
            <br><br>
            <div class="row mx-0">
                <div class="col-12">
                    <fieldset>
                        <legend class="font-weight-bold SourceSansPro biru-tua">Ijin Melakukan Pernikahan Dengan</legend>
                        <div class="row">
                            <div class="col-sm-12 biru">

                                <div class="form-group">
                                    <label class="font-weight-bold">Nama Lengkap <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="full_name" value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->full_name : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Nama Alias <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="name" value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->name : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Tempat Tanggal Lahir <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <input type="text" name="place_of_birth" value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->place_of_birth : '' }}" class="form-control" placeholder="Tempat">
                                        </div>
                                        <div class="col-md-6">
                                            <input class="form-control" type="date" value="{{($data->MaleCandidate != null) ? \Carbon\Carbon::parse($data->MaleCandidate->date_of_birth)->format('Y-m-d') : '' }}" name="date_of_birth" id="example-date-input">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Warga Negara <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="citizen" value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->citizen : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Agama <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <select id="inputState" name="religion" class="form-control">
                                        <option value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->religion : '' }}" selected>{{($data->MaleCandidate != null) ? $data->MaleCandidate->religion : '' }}</option>
                                        <option value="islam">islam</option>
                                        <option value="hindu">hindu</option>
                                        <option value="budha">budha</option>
                                        <option value="krtisten">krtisten</option>
                                        <option value="protestan">protestan</option>
                                        <option value="konghuchu">konghuchu</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Pekerjaan <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="profession" value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->profession : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Tempat Tinggal <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="residence" value="{{($data->MaleCandidate != null) ? $data->MaleCandidate->residence : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>
            <div class="text-center mt-3">
                <a href="{{route('nikah.cewe.S4suketortucewe')}}" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Back</a>
                <a href="{{route('nikah.cewe.S6sukematcewe')}}" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Next</a>
            </div>
            <br><br>
        </div>
    </div>
@endsection

resources/views/component/daftar/form/cewe/s6-sukemat.blade.php
@extends('landing')

@section('content')
    <div class="">
        <div class="container ">
            <form method="post" action="{{route('nikah.cewe.S6sukematceweSubmit')}}">
                @csrf
            <br><br>
            <h1 class="biru-tua text-center SourceSansPro">Surat Keterangan Kematian</h1>
            <br><br><br><br>
            @include('component.daftar.form.step')
            <br><br>
            <div class="row mx-0">
                <div class="col-12">
                    <fieldset>
                        <legend class="font-weight-bold SourceSansPro biru-tua">Biodata</legend>
                        <div class="row">
                            <div class="col-sm-12 biru">

                                <div class="form-group">
                                    <label class="font-weight-bold">Nama Lengkap <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="full_name" value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->full_name : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Nama Alias <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="name" value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->name : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Tempat Tanggal Lahir <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <input type="text" name="place_of_birth" value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->place_of_birth : '' }}" class="form-control" placeholder="Tempat">
                                        </div>
                                        <div class="col-md-6">
                                            <input class="form-control" type="date" value="{{($data->FemaleCandidate->extFemale != null) ? \Carbon\Carbon::parse($data->FemaleCandidate->extFemale->date_of_birth)->format('Y-m-d') : '' }}" name="date_of_birth" id="example-date-input">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Warga Negara <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="citizen" value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->citizen : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Agama <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <select id="inputState" name="religion" class="form-control">
                                        <option value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->religion : '' }}" selected>{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->religion : '' }}</option>
                                        <option value="islam">islam</option>
                                        <option value="hindu">hindu</option>
                                        <option value="budha">budha</option>
                                        <option value="krtisten">krtisten</option>
                                        <option value="protestan">protestan</option>
                                        <option value="konghuchu">konghuchu</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Pekerjaan <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="profession" value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->profession : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Tempat Tinggal <a style="font-size: 20px" class="text-danger">*</a></label>
                                    <input type="text" class="form-control" name="residence" value="{{($data->FemaleCandidate->extFemale != null) ? $data->FemaleCandidate->extFemale->residence : '' }}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukkan Hari...">
                                </div>
                            </div>

                        </div>

                    </fieldset>
                </div>
            </div>
            <div class="text-center mt-3">
                <a href="{{route('nikah.cewe.S5sujincewe')}}" class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Back</a>
                <button class="btn btn-primary" style="width: 200px;background-color: #2a92d7">Finish</button>
            </div>
            <br><br>
            </form>
        </div>
    </div>
@endsection